### ISSUE TITLE
Footer en bas de chaque page

### ISSUE THREAD

**Issue by simplix-fr** [fablab-leprototype/fablab-leprototype.github.io#5]
Ajouter un "footer" avec les coordonnées de base...

**Comment by pmauduit** [comment]
Comme c'était le cas sur elefab.org ? Celui-ci contenait les réseaux sociaux et pour l'instant on n'a pas encore décidé de ce qu'on en faisait niveau gestion

**Comment by pmauduit** [comment]
Note: j' avais mis un footer sur http://documentations.elefab.org, le site est toujours en ligne.
